# このフローの名前
name: Deploy to GitHub Page

# masterブランチにpushが走った時に呼ばれる
on:
  push:
    branches: [ master ]

jobs:
  build:
    # ubuntuで動かす
    runs-on: ubuntu-latest
    steps:
    # チェックアウトしてくる
    - uses: actions/checkout@v2
    # Node.jsのセットアップ
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    # モジュール類のセットアップ
    - run: yarn install
    # テストを流す
    - name: Test
      run: yarn run coverage
    # ビルド
    - name: Build
      run: yarn run build
    # できたファイルをそのままコミットする（変更がないと落ちるので、変更がなくても成功したことにする）
    - name: Deploy
      continue-on-error: true
      run: |
        git config --local user.email "kame-bazooka@outlook.com"
        git config --local user.name "kame-bazooka"
        git add .
        git commit -m "Deploy Application" -a
        git push origin master
    # Vercel にデプロイ
    - name: Deploy Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: "--prod"
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
        working-directory: ./